# Tomas Nesrovnal, nesro@nesro.cz, Copyright 2014
all:
	latexmk -pdf nesrotom.tex

clean:
	find . -maxdepth 1 -type f \
		\( \
		-name "*~" -o \
		-name "*.acn" -o \
		-name "*.acr" -o \
		-name "*.alg" -o \
		-name "*.aux" -o \
		-name "*.bbl" -o \
		-name "*.blg" -o \
		-name "*.dvi" -o \
		-name "*.fls" -o \
		-name "*.fdb_latexmk" -o \
		-name "*.glg" -o \
		-name "*.glo" -o \
		-name "*.gls" -o \
		-name "*.idx" -o \
		-name "*.ilg" -o \
		-name "*.ind" -o \
		-name "*.ist" -o \
		-name "*.loa" -o \
		-name "*.lof" -o \
		-name "*.log" -o \
		-name "*.lot" -o \
		-name "*.maf" -o \
		-name "*.mtc" -o \
		-name "*.mtc0" -o \
		-name "*.nav" -o \
		-name "*.nlo" -o \
		-name "*.out" -o \
		-name "*.pdfsync" -o \
		-name "*.ps" -o \
		-name "*.snm" -o \
		-name "*.synctex.gz" -o \
		-name "*.toc" -o \
		-name "*.vrb" -o \
		-name "*.xdy" -o \
		-name "*.tdo" \
		\) -delete
